package GUI;

import javax.swing.JPanel;

import javax.swing.ImageIcon;

import java.awt.Color;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import DAO.NhanVienDAO;
import Entity.NhanVien;

public class GUI_QuanLyNhanVien extends JPanel {

	private static final long serialVersionUID = 1L;

	private NhanVienDAO NV_DAO = new NhanVienDAO();

	/**
	 * Create the panel.
	 */
	public GUI_QuanLyNhanVien() {
		initComponents();
		loadData();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox<>();
		txtTimKiem = new RoundTextField(20, Color.WHITE, Color.GRAY);// Thay thế jTextField1
		jPanel2 = new javax.swing.JPanel();
		jTextField2 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setBackground(new java.awt.Color(255, 255, 255));
		setForeground(new java.awt.Color(161, 227, 249));
		setDoubleBuffered(false);
		setEnabled(false);
		setFocusable(false);
		setMaximumSize(new java.awt.Dimension(1220, 700));
		setOpaque(false);
		setPreferredSize(new java.awt.Dimension(1220, 700));
		setRequestFocusEnabled(false);

		jPanel1.setBackground(new java.awt.Color(161, 227, 249));
		jPanel1.setPreferredSize(new java.awt.Dimension(1220, 130));

		jButton1.setBackground(new java.awt.Color(161, 227, 249));
		jButton1.setIcon(new ImageIcon(GUI_QuanLyNhanVien.class.getResource("/view/icon/icon_capnhat.png"))); // NOI18N
		jButton1.setText("CẬP NHẬT");
		jButton1.setAlignmentY(0.0F);
		jButton1.setBorderPainted(false);
		jButton1.setContentAreaFilled(false);
		jButton1.setDefaultCapable(false);
		jButton1.setFocusPainted(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton4.setBackground(new java.awt.Color(161, 227, 249));
		jButton4.setIcon(new ImageIcon(GUI_QuanLyNhanVien.class.getResource("/view/icon/icon_xoa.png"))); // NOI18N
		jButton4.setText("XÓA");
		jButton4.setAlignmentY(0.0F);
		jButton4.setBorderPainted(false);
		jButton4.setContentAreaFilled(false);
		jButton4.setDefaultCapable(false);
		jButton4.setFocusPainted(false);
		jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(161, 227, 249));
		jButton3.setIcon(new ImageIcon(GUI_QuanLyNhanVien.class.getResource("/view/icon/icon_them.png"))); // NOI18N
		jButton3.setText("THÊM");
		jButton3.setAlignmentY(0.0F);
		jButton3.setBorderPainted(false);
		jButton3.setContentAreaFilled(false);
		jButton3.setDefaultCapable(false);
		jButton3.setFocusPainted(false);
		jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhân viên", "Tên", "Số điện thoại" }));
		jComboBox1.setMaximumSize(new java.awt.Dimension(184, 65));
		jComboBox1.setMinimumSize(new java.awt.Dimension(184, 65));
		jComboBox1.setPreferredSize(new java.awt.Dimension(184, 65));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		txtTimKiem.setText("Tìm kiếm");
		txtTimKiem.setMaximumSize(new java.awt.Dimension(362, 65));
		txtTimKiem.setMinimumSize(new java.awt.Dimension(362, 65));
		txtTimKiem.setName(""); // NOI18N
		txtTimKiem.setPreferredSize(new java.awt.Dimension(362, 65));

		// Thêm sự kiện focus để xử lý placeholder
		txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if (txtTimKiem.getText().equals("Tìm kiếm")) {
					txtTimKiem.setText("");
				}
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				if (txtTimKiem.getText().isEmpty()) {
					txtTimKiem.setText("Tìm kiếm");
				}
			}
		});
		txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(59, 59, 59).addComponent(jButton3)
						.addGap(30, 30, 30).addComponent(jButton1).addGap(31, 31, 31).addComponent(jButton4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(58, 58, 58)
						.addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(61, 61, 61)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(27, 27, 27)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(24, Short.MAX_VALUE)));

		jPanel2.setBackground(new java.awt.Color(0, 163, 239));
		jPanel2.setPreferredSize(new java.awt.Dimension(1220, 60));

		jTextField2.setBackground(new java.awt.Color(0, 163, 239));
		jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		jTextField2.setText("DANH SÁCH THÔNG TIN NHÂN VIÊN");
		jTextField2.setBorder(null);
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 60, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));

		jScrollPane1.setMaximumSize(null);
		jScrollPane1.setMinimumSize(null);
		jScrollPane1.setPreferredSize(null);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null } },
				new String[] { "STT", "Mã nhân viên", "Tên", "SDT", "Email", "Giới tính", "Chức vụ" }));
		jTable1.setPreferredSize(null);
		jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
		jTable1.setFillsViewportHeight(true);

		// Căn giữa nội dung trong các ô và tiêu đề cột
		javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
		centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

		// Áp dụng căn giữa cho tất cả các cột
		for (int i = 0; i < jTable1.getColumnCount(); i++) {
			jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
		}

		// Căn giữa tiêu đề cột
		((javax.swing.table.DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
				.setHorizontalAlignment(javax.swing.JLabel.CENTER);

		jScrollPane1.setViewportView(jTable1);
		if (jTable1.getColumnModel().getColumnCount() > 0) {
			jTable1.getColumnModel().getColumn(0).setMinWidth(60);
			jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
			jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
			jTable1.getColumnModel().getColumn(1).setMinWidth(120);
			jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
			jTable1.getColumnModel().getColumn(1).setMaxWidth(120);
			jTable1.getColumnModel().getColumn(2).setMinWidth(200);
			jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
			jTable1.getColumnModel().getColumn(2).setMaxWidth(350);
			jTable1.getColumnModel().getColumn(3).setMinWidth(120);
			jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
			jTable1.getColumnModel().getColumn(3).setMaxWidth(120);
			jTable1.getColumnModel().getColumn(4).setMinWidth(250);
			jTable1.getColumnModel().getColumn(4).setPreferredWidth(250);
			jTable1.getColumnModel().getColumn(5).setMinWidth(100);
			jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
			jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
			jTable1.getColumnModel().getColumn(6).setMinWidth(150);
			jTable1.getColumnModel().getColumn(6).setPreferredWidth(150);
			jTable1.getColumnModel().getColumn(6).setMaxWidth(250);
		}

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)));
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// Xử lý sự kiện cập nhật nhân viên
		int selectedRow = jTable1.getSelectedRow();
		if (selectedRow != -1) {
			String maNhanVien = jTable1.getValueAt(selectedRow, 1).toString();
			NhanVien nv = NV_DAO.getNhanVienById(maNhanVien);
			if (nv != null) {
				// Gọi dialog cập nhật nhân viên
				UpdateNhanVienDialog dialog = new UpdateNhanVienDialog(null, true, this, nv);
				dialog.setVisible(true);
			}
		} else {
			javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật!");
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// Xử lý sự kiện xóa nhân viên
		int selectedRow = jTable1.getSelectedRow();
		if (selectedRow != -1) {
			String maNhanVien = jTable1.getValueAt(selectedRow, 1).toString();
			int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhân viên này?",
					"Xác nhận xóa", javax.swing.JOptionPane.YES_NO_OPTION);
			if (confirm == javax.swing.JOptionPane.YES_OPTION) {
				boolean result = NV_DAO.delete(maNhanVien);
				if (result) {
					javax.swing.JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
					loadData();
				} else {
					javax.swing.JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại!");
				}
			}
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// Xử lý sự kiện thêm nhân viên
		CreateNhanVienDialog dialog = new CreateNhanVienDialog(null, true, this);
		dialog.setVisible(true);
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		String searchText = txtTimKiem.getText().trim();
		String searchType = (String) jComboBox1.getSelectedItem();

		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0);

		List<NhanVien> nhanViens = NV_DAO.searchNhanVien(searchType, searchText);
		int stt = 1;

		for (NhanVien nv : nhanViens) {
			model.addRow(new Object[] { stt++, nv.getMaNhanVien(), nv.getTen(), nv.getSdt(), nv.getEmail(),
					nv.getGioiTinh(), nv.getChucVu() });
		}
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	public void loadData() {
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0); // Xóa tất cả các dòng hiện có

		List<NhanVien> listNhanVien = NV_DAO.getAllNhanVien();
		int stt = 1;

		for (NhanVien nv : listNhanVien) {
			model.addRow(new Object[] { stt++, nv.getMaNhanVien(), nv.getTen(), nv.getSdt(), nv.getEmail(),
					nv.getGioiTinh(), nv.getChucVu() });
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private RoundTextField txtTimKiem; // Thay thế jTextField1
	private javax.swing.JTextField jTextField2;
	// End of variables declaration
}
